
/*
 * This file was generated by the Gradle 'init' task.
 */

group = "org.example"
version = "1.0-SNAPSHOT"

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    api(project(":list"))
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "$group"
            artifactId = "utilities"

            from(components["java"])
        }
    }
}
