/*
 * This file was generated by the Gradle 'init' task.
 */

group = "org.example"
version = "1.0-SNAPSHOT"

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "$group"
            artifactId = "app"

            from(components["java"])
        }
    }
}